version: "2"
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 75
  nested-control-flow:
    config:
      threshold: 8
  return-statements:
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: 10
  identical-code:
    enabled: true
    config:
      threshold: 10
plugins:
 eslint:
  enabled: true
exclude_patterns:
- "config/"
- "db/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "**/vendor/"
- "**/*.d.ts"
- "**/assets/"